EDITOR_PLAYER_TAG = "[ІМ'Я ГРАВЦЯ]"
ORIGINAL_PLAYER_TAG = "{Player}"
DEFAULT_GAME_DIALOG_MAX_WIDTH_PIXELS = 240
DEFAULT_LINE_WIDTH_WARNING_THRESHOLD = 175

GENERAL_APP_FONT_FAMILY = "Segoe UI"
MONOSPACE_EDITOR_FONT_FAMILY = "Courier New"
DEFAULT_APP_FONT_SIZE = 10