# core/context.py
from typing import Protocol, Optional, Any, Dict, List, Tuple
from PyQt5.QtWidgets import QStatusBar, QWidget

class UIProvider(Protocol):
    @property
    def statusBar(self) -> Optional[QStatusBar]: ...
    def force_focus(self) -> None: ...
    @property
    def preview_text_edit(self) -> QWidget: ...
    @property
    def original_text_edit(self) -> QWidget: ...
    @property
    def edited_text_edit(self) -> QWidget: ...
    @property
    def block_list_widget(self) -> QWidget: ...

class ProjectContext(Protocol):
    @property
    def project_manager(self) -> Any: ...
    @property
    def settings_manager(self) -> Any: ...
    @property
    def state(self) -> Any: ...
    @property
    def data_processor(self) -> Any: ...
    @property
    def ui_updater(self) -> Any: ...
    @property
    def ui_provider(self) -> UIProvider: ...
    
    # Data access
    @property
    def data(self) -> List[Any]: ...
    @property
    def edited_file_data(self) -> List[Any]: ...
    @property
    def edited_data(self) -> Dict[Tuple[int, int], str]: ...
    
    @property
    def current_block_idx(self) -> int: ...
    @property
    def current_string_idx(self) -> int: ...
    
    @property
    def current_game_rules(self) -> Any: ...
    
    @property
    def unsaved_changes(self) -> bool: ...
    @unsaved_changes.setter
    def unsaved_changes(self, value: bool) -> None: ...

    def update_title(self) -> None: ...
