from PyQt5.QtGui import QColor
from PyQt5.QtCore import Qt

# --- Light Theme Colors ---
LT_CURRENT_LINE_COLOR = QColor("#E8F2FE")
LT_LINKED_CURSOR_BLOCK_COLOR = QColor("#F0F8FF")
LT_PREVIEW_SELECTED_LINE_COLOR = QColor("#CDE8FF")

# --- Dark Theme Colors ---
DT_CURRENT_LINE_COLOR = QColor("#3A3A3A")
DT_LINKED_CURSOR_BLOCK_COLOR = QColor("#333333")
DT_PREVIEW_SELECTED_LINE_COLOR = QColor("#004A7E")


# --- Common Colors (Alpha values can be used for blending) ---
LINKED_CURSOR_POS_COLOR = QColor(0, 120, 215, 60)
TAG_INTERACTION_HIGHLIGHT_COLOR = QColor(0, 255, 0, 60)
SEARCH_MATCH_HIGHLIGHT_COLOR = QColor(255, 165, 0, 100)
WIDTH_EXCEEDED_LINE_COLOR = QColor(255, 0, 0, 100)
SHORT_LINE_COLOR = QColor(0, 255, 0, 100)
EMPTY_ODD_SUBLINE_COLOR = QColor(255, 165, 0, 180)
NEW_BLUE_SUBLINE_COLOR = QColor(0, 0, 255, 120) 


# --- Dynamic Colors (Will be set in LineNumberedTextEdit) ---
CURRENT_LINE_COLOR = LT_CURRENT_LINE_COLOR
LINKED_CURSOR_BLOCK_COLOR = LT_LINKED_CURSOR_BLOCK_COLOR
PREVIEW_SELECTED_LINE_COLOR = LT_PREVIEW_SELECTED_LINE_COLOR


# --- Unused or less important colors ---
CRITICAL_PROBLEM_LINE_COLOR = QColor(255, 255, 0, 80)
WARNING_PROBLEM_LINE_COLOR = QColor(221, 221, 221, 150)
CHARACTER_LIMIT_LINE_POSITION = 32
CHARACTER_LIMIT_LINE_COLOR = QColor(0, 0, 0, 0)
CHARACTER_LIMIT_LINE_WIDTH = 1
CHARACTER_LIMIT_LINE_STYLE = Qt.SolidLine
WIDTH_THRESHOLD_LINE_COLOR = QColor(0, 128, 0, 120)
WIDTH_THRESHOLD_LINE_WIDTH = 3
WIDTH_THRESHOLD_LINE_STYLE = Qt.DashLine
PAIR_SEPARATOR_LINE_COLOR = QColor(0, 100, 0) 
PAIR_SEPARATOR_LINE_STYLE = Qt.SolidLine
PAIR_SEPARATOR_LINE_THICKNESS = 1